---
AWSTemplateFormatVersion: '2010-09-09'

Description:  This template deploys a VPC, with a pair of interconnect, application and data subnets spread
  across two Availability Zones.


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Dev

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: Devv
