AWSTemplateFormatVersion: '2010-09-09'

version: 0.2

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: ApplicationVpc
        
Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: AppVPC
    
    
